clean-cycle: 15 # remove empty raids every 15 seconds
raid-world-prefix: partyraids
raids:
  example:
    dungeon: arena
    difficulty: normal
    spawn-location: 0, 0, 0
    join-criteria:
      minimum-party-size: 1
      minimum-level: 1
    join-in: 5 # number of seconds for the online to join
    on-startup:
      clear-mobs: true
      mobs:
        1:
          type: VILLAGER
          location: 1, 2, 3
      commands:
        - day day @w
